listen_addr: ":5555"
log_level: "debug"
metrics:
  addr: ":9090"
  enabled: true

forky:
  retentionPeriod: "30m"

  store:
    type: memory

  indexer:
    dsn: ":memory:"
    driver_name: sqlite

  sources:
    - name: "example"
      type: "beacon_node"
      config:
        beaconAddress: "http://localhost:5052"
        pollingInterval: "12s"
        cacheTtlSeconds: 300
  
  ethereum:
    network:
      # name: "mainnet"
      # spec:
      #   seconds_per_slot: 12
      #   slots_per_epoch: 32
      #   genesis_time: 1606824023

      # name: "goerli"
      # spec:
      #   seconds_per_slot: 12
      #   slots_per_epoch: 32
      #   genesis_time: 1616508000   

      # name: "sepolia"
      # spec:
      #   seconds_per_slot: 12
      #   slots_per_epoch: 32
      #   genesis_time: 1655733600