listenAddr: ":5555"
logging: "debug" # panic,fatal,warm,info,debug,trace
metricsAddr: ":9090"

forky:
  retentionPeriod: "30m"

  store:
    type: memory

  indexer:
    dsn: ":memory:"
    driver_name: sqlite

  sources:
    - name: "example"
      type: "beacon_node"
      config:
        beaconAddress: "http://localhost:5052"
        pollingInterval: "12s"
        cacheTtlSeconds: 300
