listen_addr: ":5555"
log_level: "debug"
metrics:
  addr: ":9090"
  enabled: true

forky:
  retentionPeriod: "30m"

  store:
    type: memory

  indexer:
    dsn: ":memory:"
    driver_name: sqlite

  sources:
    - name: "example"
      type: "beacon_node"
      config:
        beaconAddress: "http://localhost:5052"
        pollingInterval: "12s"
        cacheTtlSeconds: 300
